/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AuthForm: typeof import('./src/components/auth/AuthForm.vue')['default']
    ErrorDialog: typeof import('./src/components/ErrorDialog.vue')['default']
    FeedbackDialog: typeof import('./src/components/FeedbackDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RespAppBar: typeof import('./src/components/resp/RespAppBar.vue')['default']
    RespBottomNav: typeof import('./src/components/resp/RespBottomNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
